// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIcbHe3lKgcwGzICsgripyQuPii-EW1TQ',
    appId: '1:383205435470:web:7b21014ba9e85ea8f4bb1f',
    messagingSenderId: '383205435470',
    projectId: 'clinicaldietbase',
    authDomain: 'clinicaldietbase.firebaseapp.com',
    storageBucket: 'clinicaldietbase.firebasestorage.app',
    measurementId: 'G-8MQJ8C4G3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2DC5_kmLITNONx5pSqm4vY1UL8WX-hj8',
    appId: '1:383205435470:android:8bd2faa634aa8da2f4bb1f',
    messagingSenderId: '383205435470',
    projectId: 'clinicaldietbase',
    storageBucket: 'clinicaldietbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx8k__ePsDHbpR83_xOUwtVDRSHBM-kCo',
    appId: '1:383205435470:ios:c6a93b31bb9ab5a1f4bb1f',
    messagingSenderId: '383205435470',
    projectId: 'clinicaldietbase',
    storageBucket: 'clinicaldietbase.firebasestorage.app',
    iosBundleId: 'com.polije.clinicalDiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIcbHe3lKgcwGzICsgripyQuPii-EW1TQ',
    appId: '1:383205435470:web:f56b1be51c52ededf4bb1f',
    messagingSenderId: '383205435470',
    projectId: 'clinicaldietbase',
    authDomain: 'clinicaldietbase.firebaseapp.com',
    storageBucket: 'clinicaldietbase.firebasestorage.app',
    measurementId: 'G-5ELEMV5B49',
  );
}
